# theme: minima  # Or any supported Jekyll theme
remote_theme: mmistakes/minimal-mistakes
plugins:
  - jekyll-include-cache

# Enable navigation links
header_pages:
  - index.md
  - projects.md
  - contact.md

# Site details
title: Research Profile
author: Fuminaba
description: "Welcome to my site powered by Jekyll"